--module Models.Direction exposing (Direction(..), all, delta)

--type Direction = North
--               | South
--               | East
--               | West
--               | Northeast
--               | Northwest
--               | Southeast
--               | Southwest
--
--all =
--  [ North
--  , South
--  , East
--  , West
--  , Northeast
--  , Northwest
--  , Southeast
--  , Southwest
--  ]
--
